version: 2
jobs:
  build-publish:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Build, test, publish
          command: ./pipe_build_up_test.sh

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-publish:
          context: cyberdojo-tools-context
          filters:
            branches:
              only: [ master ]
