name: Main

on:
  push:
    branches:
      - master

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACKAGES_USERNAME: ${{ github.actor }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and publish image
        run:
          ./pipe_build_up_test.sh