name: Main

on:
  push:
    branches:
      - master

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env: 
      PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PACKAGES_USERNAME: ${{ github.actor }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Install buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish image
        run:
          ./pipe_build_up_test.sh